services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    # Chỉ map port 80 nếu bạn muốn truy cập trực tiếp qua IP máy chủ, 
    # nhưng tốt nhất là để Nginx Backend làm proxy.
    ports:
      - "3000:80" 
    env_file:
      - .env
    networks:
      - tro-go-network
    restart: always

networks:
  tro-go-network:
    external: true
