services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    networks:
      - tro-go-network
    restart: always

networks:
  tro-go-network:
    external: true
