server {
    listen 80;
    server_name motel.codetoolkit.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name motel.codetoolkit.org;

    # Lấy chứng chỉ từ đường dẫn giống Backend
    ssl_certificate /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/private.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tắt log các file không quan trọng để sạch log
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Cache file tĩnh
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
